### ISSUE TITLE
Loading The Same Save Causes Screen Tear

### ISSUE THREAD

**Issue by DubStepMad** [thale5/LSM#9]
Loading the save first time around works perfectly.

When exiting to the main screen and loading the save again causes the screen texture to be really zoomed in and unplayable.

The fix is to restart the game again but this shouldn't be a permanent fix.

**Comment by originalfoo** [comment]
That's due to way game engine works; it provides very confusing info to mods (all mods) that makes it hard for them to keep track of actual game state - this is the tangled mess that mods are expected to deal with (but rarely do due to limited dev time that modders have):

![CitiesSkylines_EventFlow](https://user-images.githubusercontent.com/1386719/73421614-632a0700-431e-11ea-9fee-a6ae2b62f982.png)

Most mods will break if you do a second load in the same Cities: Skyline session - so always exit to desktop before loading another save.

**Comment by thale5** [comment]
When in game, there is a huge difference between loading from the same biome (for example Tropical) and loading from another biome. Unfortunately the game does not expose this difference to mods in a sufficient manner.

It is not unsolvable for LSM but for some other "big" mods, it is an impossible situation.
